version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: protokit-postgres
    profiles:
      - db
      - postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=protokit
    networks:
      - db-net

  redis:
    image: redis:6.2-alpine
    container_name: protokit-redis
    profiles:
      - db
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server /redis.conf --requirepass password
    volumes:
      - ../data/redis:/data
      - ./redis.conf:/redis.conf
    networks:
      - db-net

networks:
  db-net: