version: '3.9'

include:
  - ./persistence/docker-compose.yml

services:
  sequencer:
    image: protokit-base
    build:
      dockerfile: ./packages/deployment/docker/base/Dockerfile
      context: ../../..
    container_name: protokit-sequencer
    environment:
      - DATABASE_URL=${POSTGRES_URL}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - db-net
    ports:
      - "8080:8080"
    command: ["${INDEX_JS}", "${PROTOKIT_ENV}", "${PROTOKIT_CONFIG}"]
